# Generated by Django 3.2.19 on 2023-06-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
